fsm:
  flight_type: 1 
  thresh_replan: 1.5
  thresh_no_replan: 2.0
  waypoint_num: 2 
  waypoint0_x: 19.0
  waypoint0_y: 0.0
  waypoint0_z: 1.0
  waypoint1_x: -19.0
  waypoint1_y: 0.0
  waypoint1_z: 1.0
  waypoint2_x: 0.0
  waypoint2_y: 19.0
  waypoint2_z: 1.0

sdf_map:
  resolution: 0.1
  map_size_x: 40.0 
  map_size_y: 20.0
  map_size_z: 5.0
  local_update_range_x: 5.5
  local_update_range_y: 5.5
  local_update_range_z: 4.5
  obstacles_inflation: 0.099
  local_bound_inflate: 0.0
  local_map_margin: 50
  ground_height: -1.0
  cx: 321.04638671875
  cy: 243.44969177246094
  fx: 387.229248046875
  fy: 387.229248046875
  use_depth_filter: true
  depth_filter_tolerance: 0.15
  depth_filter_maxdist: 5.0
  depth_filter_mindist: 0.2
  depth_filter_margin: 2
  k_depth_scaling_factor: 1000.0
  skip_pixel: 2
  p_hit: 0.65
  p_miss: 0.35
  p_min: 0.12
  p_max: 0.90
  p_occ: 0.80
  min_ray_length: 0.5
  max_ray_length: 4.5
  esdf_slice_height: 0.3
  visualization_truncate_height: 2.49
  virtual_ceil_height: 2.5
  show_occ_time: false
  show_esdf_time: false
  pose_type: 1
  frame_id: world

manager:
  max_vel: 3.0 
  max_acc: 2.0 
  max_jerk: 4.0
  dynamic_environment: 0
  local_segment_length: 6.0
  clearance_threshold: 0.2
  control_points_distance: 0.5
  use_geometric_path: false
  use_kinodynamic_path: true
  use_topo_path: false
  use_optimization: true

search:
  max_tau: 0.6
  init_max_tau: 0.8
  max_vel: 3.0
  max_acc: 2.0 
  w_time: 10.0
  horizon: 7.0
  lambda_heu: 5.0
  resolution_astar: 0.1
  time_resolution: 0.8
  margin: 0.2
  allocate_num: 100000
  check_num: 5

optimization:
  lambda1: 10.0
  lambda2: 5.0
  lambda3: 0.00001
  lambda4: 0.01
  lambda7: 100.0
  dist0: 0.4
  max_vel: 3.0
  max_acc: 2.0 
  algorithm1: 15
  algorithm2: 11
  max_iteration_num1: 2
  max_iteration_num2: 300
  max_iteration_num3: 200
  max_iteration_num4: 200
  max_iteration_time1: 0.0001
  max_iteration_time2: 0.005
  max_iteration_time3: 0.003
  max_iteration_time4: 0.003
  order: 3

bspline:
  limit_vel: 3.0 
  limit_acc: 2.0
  limit_ratio: 1.1